INSERT INTO public.message_templates (key, body) VALUES
  ('fallback', 'Use the menu below.'),
  ('payment_invalid_reference', 'Send only the reference (letters/digits, 4–40 chars), or upload a clear receipt image.'),
  ('payment_reference_verifying', '⏳ Verifying your payment…'),
  ('payment_receipt_verifying', '⏳ Verifying your receipt…'),
  ('payment_receipt_download_failed', '❌ Could not read that receipt file. Reason: {reason}\n\nPlease upload a clear image receipt or paste the transaction reference.'),
  ('payment_waiting_manual', '✅ Your payment was verified successfully.\n\nYour order *{short_id}* is waiting for manual delivery by admin. You will be notified here as soon as it is delivered.'),
  ('payment_error_order_missing', 'Order not found.'),
  ('payment_error_order_not_pending', 'Order is {order_status}, cannot verify.'),
  ('payment_error_no_method', 'Pick a payment method first.'),
  ('payment_error_expired', 'Order has expired.'),
  ('payment_error_receiver_mismatch', '{reason}'),
  ('payment_error_no_amount', 'Could not read amount from receipt.'),
  ('payment_error_amount_mismatch', 'Amount mismatch. Expected {expected} ETB, receipt shows {received} ETB.'),
  ('payment_error_out_of_stock', 'Out of stock — contact support, your payment is recorded.'),
  ('payment_error_duplicate_reference', 'This reference was already used.'),
  ('payment_error_finalize_failed', 'Could not finalize delivery. Contact support.'),
  ('payment_error_not_found', 'We could not find this reference on Telebirr or CBE yet. CBE can take 1–5 minutes to publish a transaction. Please wait a moment and resend the same reference, and double-check it matches your SMS exactly.'),
  ('payment_error_unauthorized', 'Verification service is misconfigured. Please contact support.'),
  ('payment_error_network', 'Network issue while contacting the verification service. Please try again in a moment.'),
  ('payment_error_timeout', 'Verification timed out. Please try again.'),
  ('payment_error_generic', 'Could not verify this reference ({error}). Make sure you sent to our Telebirr or CBE account and copied the reference exactly from your SMS.'),
  ('payment_error_service_unavailable', 'Verification service is unavailable. Please try again in a moment.'),
  ('payment_error_duplicate_receipt', 'This receipt image was already used.'),
  ('payment_error_receipt_service_unavailable', 'Receipt verification is unavailable. Please try again in a moment.'),
  ('payment_error_receipt_generic', 'Could not verify this receipt image ({error}). Please send a clear screenshot/photo of the full Telebirr or CBE receipt.'),
  ('wallet_deposit_reference_prompt', 'Send the transaction reference or upload a clear receipt image here.'),
  ('wallet_deposit_invalid_reference', 'Send only the reference (letters/digits, 4–40 chars), or upload a clear receipt image.'),
  ('wallet_deposit_reference_verifying', '⏳ Verifying deposit…'),
  ('wallet_deposit_receipt_verifying', '⏳ Verifying your deposit receipt…'),
  ('wallet_deposit_receipt_download_failed', '❌ Could not read that receipt file. Reason: {reason}'),
  ('wallet_deposit_error_duplicate_reference', '❌ This reference was already used.'),
  ('wallet_deposit_error_verify_failed', '❌ Could not verify this payment. Reason: {reason}'),
  ('wallet_deposit_error_amount_mismatch', '❌ Amount mismatch. Expected {expected} ETB, receipt shows {received} ETB.'),
  ('wallet_deposit_error_receiver_mismatch', '❌ {reason}'),
  ('wallet_deposit_error_failed', '❌ Failed: {reason}'),
  ('wallet_deposit_success', '✅ Deposited *{amount} ETB*. New balance: *{balance} ETB*.')
ON CONFLICT (key) DO NOTHING;
